/**
 * Authentication Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The password hash is injected during the CI/CD build process
 * from the ACCESS_PASSWORD secret configured in GitHub repository settings
 */

const AUTH_CONFIG = {
    /**
     * SHA-256 hash of the access password
     * This will be replaced during GitHub Actions workflow execution
     */
    passwordHash: '883b6f5a4f47ca0cab0c7008d6105f00f476da7018b81f04697cc047f26f2689',

    /**
     * Session duration in milliseconds
     * Default: 7 days (604800000 ms)
     */
    sessionDuration: 7 * 24 * 60 * 60 * 1000,

    /**
     * LocalStorage key for storing authentication token
     */
    storageKey: 'arxiv_auth_token',

    /**
     * LocalStorage key for storing session expiration time
     */
    storageExpireKey: 'arxiv_auth_expire'
};
